# Generated by Django 4.0.5 on 2022-06-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducatorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('OutDate', models.DateField()),
                ('InDate', models.DateField()),
                ('ClassName', models.CharField(max_length=50, unique=True)),
                ('MobNo', models.BigIntegerField()),
            ],
        ),
    ]
